server:
  port: 8761

spring:
    application:
        name: eureka
eureka: # 注册中心
    environment: dev # 页面上显示的environment
    data-center: dev # 页面上显示的data-center
    instance: # 服务实例
        lease-renewal-interval-in-seconds: 30 # 续约间隔
        lease-expiration-duration-in-seconds: 90 # 租约到期时间
    client: # 客户端
        fetch-registry: false # 拉取注册表
        register-with-eureka: false # 注册
        registry-fetch-interval-seconds: 30 # 拉取注册表间隔
        service-url: # 注册中心url
            defaultZone: http://localhost:${server.port}/eureka/ # 默认区/Users/lixiaobin/git/hdhxby/netflix-example/netflix-zuul-application/pom.xml
    server: # 服务端
        enable-self-preservation: false #关闭自我保护
