server:
    port: 8888

spring:
    application:
        name: configserver
    cloud:
        config:
            enabled: true # 默认为true
            server:
                git:
                    uri: https://github.com/hdhxby/configuration
                    default-label: master # 正常通过命令行初始化的为master,github通过页面创建的仓库默认分之为main
#                    clone-on-start: true
management:
    endpoints:
        web:
            exposure:
                include: "*"
    endpoint:
        health:
            show-details: ALWAYS