spring:
    main:
        allow-bean-definition-overriding: true
    profiles:
        include:
            - logging
management:
    endpoints:
        web:
            exposure:
                include: "*"
    endpoint:
        health:
            show-details: ALWAYS
