server:
  port: 8443

spring:
  application:
    name: zuul
zuul: # ZuulProperties
  debug:
    request: true # 是否debug @see DynamicPropertyFactory
    parameter: debug # 请求url中的debug标志 @see DynamicPropertyFactory
  include-debug-header: true # SendResponseFilter会用到
  ribbon:
    eager-load:
      enabled: false # 预加载, 会初始化ZuulRouteApplicationContextInitializer
  retryable: true # 重试
  routes: # 路由 Map<String, ZuulRoute>
    hello:
      path: /api/hello/**
      serviceId: hello
      stripPrefix: false
    world:
      path: /api/world/**
      serviceId: world
      stripPrefix: false

# 负载均衡
ribbon: # TODO AbstractRibbonCommand里面,具体分析
  ConnectTimeout: 30000 # 连接超时
  ReadTimeout: 30000 # 读取超时
  OkToRetryOnAllOperations: true
  MaxAutoRetries: 1 # 其他机器重试次数
  MaxAutoRetriesNextServer: 3 # 故障机器重试次数
